pydiscourse/pydiscourse

pydiscourse/sso.py
When trying to use the library I encountered the following error message upon redirecting to Discourse: `Account login timed out, please try logging in again.`. 
Looking at the payload received from Discourse, it was something like `nonce=XXXX&return_sso_url=http%3A%2F%2Fcommunity.mywebsite.com%2Fsession%2Fsso_login`
I can't find good documentation for this but I think their intention is to return a querystring with multiple variables, one of which is the `nonce` the other is the redirect URL. Instead of splitting on `=` I used `parse_qs` to parse the payload. That solved the problem for me and should generally work better even when this problem does not exist.
=> Only return `nonce` from given payload

pydiscourse/client.py, tests/test_client.py
Hi!
I'm using pydiscourse to consume Discourse API, but I saw that Badges endpoint isn't in pydiscourse. Then I made it! :)
=> Added badges endpoint to pydiscourse

pydiscourse/client.py
This method adds the group to the user object. With the current version of Discourse the add_user_to_group did not work either on the website's admin or via the API (even thou it returned ok). This might be a Discourse bug, but I didn't have time to investigate.
=> Added method to add group to the user

pydiscourse/client.py, tests/test_client.py
Send request params in the request body instead of the query string. This avoid a `pydiscourse.exceptions.DiscourseClientError: Request-URI Too Large` error when updating large amounts of data. 
I tested this on `update_post` which is where I was running into this error but didn't test any additional methods.
=> pass params in data

setup.py
With the addition of json support in PR #9, the required version of requests has increased to that which introduced json={} syntax.
=> Increase minimum requests version

AUTHORS, pydiscourse/client.py, tests/test_client.py
The Discourse API is changing to only accept [authentication via headers](https://meta.discourse.org/t/discourse-api-documentation/22706).
There currently isn't a defined [timeline](https://meta.discourse.org/t/discourse-api-documentation/22706/265) on the API change.
This PR changes the `DiscourseClient._request()` method to pass the API key and username via headers rather than via params.
Closes bennylope/pydiscourse#27
=> Authenticate via headers

pydiscourse/client.py
Changed the group() function in client.py to use the correct API endpoint to get group information. It was previously getting group members instead.
=> Fix call to get group info by name

pydiscourse/client.py
Prevents Discourse from returning `413 Payload too large` errors due to an empty JSON object being submitted with requests that don't otherwise specify the `json=` argument.
Requests correctly handles `None` being passed to keyword arguments, but does not ignore empty dictionaries.
Closes #35
=> Fix 413 response from Discourse due to empty dict passed as json

.github/workflows/pypi.yml
GitHub workflow to build and publish package to PyPI when a tagged commit is pushed to the master branch _or_ when a manual release is drafted.
@bennylope you (I assume you, at least) will need to generate two encrypted secrets, namely `PYPI_USERNAME` and `PYPI_PASSWORD`, for this to work (see https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets).
=> Add workflow to publish package to PyPI on tag/release (fixes #43)

pydiscourse/client.py
Following this review : https://github.com/bennylope/pydiscourse/pull/49#discussion_r568536975, I found why we needed to check for errors length.
When making calls with Data Explorer, the request looks like
```
POST /admin/plugins/explorer/queries/1/run
200 '{"success":true,"errors":[],"duration":4.2,"result_count":0,"params":{},"columns" ["id","username"],"default_limit":1000,"relations":{},"colrender":{},"rows":[]}'
```
Without the changes included in this PR, a successful request throws an error (`DiscourseError No exception message supplied`).
Thanks !
=> fix(errors): handle data-explorer responses

pydiscourse/client.py
This adds an interface for the `/post_action_users` endpoint, which can be used to see who liked a post. See https://meta.discourse.org/t/getting-who-liked-a-post-from-the-api/103618 for context. (I didn't end up needing this, but I figured I would at least try to contribute it back.)
=> Add post_action_users to see who liked a post

src/pydiscourse/client.py
Fixed getting category details. https://docs.discourse.org/#operation/getCategory
=> Fix getting category details

src/pydiscourse/client.py
Closes #61
Use the new API for adding group owners.
=> Use new API for add_group_owner

src/pydiscourse/client.py
Closes #64
Add an `add_group_owners` method to add multiple owners by list.
This is based on #63, please merge that one before this one.
=> Add group owners

src/pydiscourse/client.py
Two changes here, happy to split if you would prefer.
- First, with my Discourse instance (v2.8.13 on nginx, in case it makes a difference), I encountered rate-limited responses that did not have a `Content-Type` header. The first commit makes it so that the code takes these in stride.
- The second commit includes information from the `Discourse-Rate-Limit-Error-Code`, which makes it easier to debug which limit is encountered. Also, logging happens before waiting, to provide feedback on what is happening.
=> Rate limit improvements

.github/workflows/test.yml
test.yml uses the wrong python version variable which is causing it to not display the title correctly in the github actions interface, see github documentation here:
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-the-python-starter-workflow
=> Fix python version display in github actions

.gitignore, CONTRIBUTING.rst, src/pydiscourse/client.py, tests/test_client.py
Added endpoint for looking up latest posts across topics, see Discourse api documentation here:
https://docs.discourse.org/#tag/Posts/operation/listPosts
Also corrected incorrect requirements file name in documentation and added .gitignore sections for PyCharm and `pyenv`.
=> Add endpoint to fetch latest posts across topics

src/pydiscourse/client.py, tests/test_client.py
Add endpoint to update category settings via the api. I have tested that the new method adds a new tag group to an existing category against my Discourse instance, see the example code below:
```
from munch import DefaultMunch
...
category = DefaultMunch.fromDict(discourse_client.category(category_id)["category"])
if STAFF_ONLY_TAG_GROUP_NAME not in category.allowed_tag_groups:
category.allowed_tag_groups.append(STAFF_ONLY_TAG_GROUP_NAME)
discourse_client.update_category(
category_id, allowed_tag_groups=category.allowed_tag_groups
)
```
=> Add client endpoint for updating category

src/pydiscourse/client.py
Change the URLs and delete request to match API docs, see:
- https://docs.discourse.org/#tag/Groups/operation/addGroupMembers
- https://docs.discourse.org/#tag/Groups/operation/removeGroupMembers
Note that group member removal is currently affected by https://github.com/discourse/discourse/pull/23042.
=> Fix group membership admin functionality

src/pydiscourse/client.py
Update implementation of adding a single or multiple group owners following [the source code](https://github.com/discourse/discourse/blob/0bd64788d2b4680c04fbef76314a24884d65fed9/app/assets/javascripts/discourse/app/models/group.js#L151-L154)
Closes #76
=> use an up to date endpoint for group owner creation

src/pydiscourse/client.py, tests/test_client.py
Add a wrapper for the `/posts/by_number` endpoint. This endpoint seems undocumented, but it parallels the way share URLs for a specific post are created: it allows retrieving a post by referencing its creation number inside the topic it belongs to, instead of its global `post_id`.
=> Add a wrapper for the /posts/by_number endpoint

src/pydiscourse/client.py, tests/test_client.py
Hello there!
This PR simply add the `about` endpoint for discourse instance statistic like total post number, etc.
=> add about endpoint for site statistics
