pydiscourse/client.py

Groups method returns the list of all groups.
Created group_owners which allows you to add and delete owners.
Created group_members which allows you to add and delete members.

Added partial groups support

---

pydiscourse/client.py

This PR adds the following functions:
- user_all: returns more data on a user that traditional user
- group, create_group, delete_group, group_owners, group_members:  several missing functionalities for groups.

Adding some API calls, notably on groups and users

---

pydiscourse/client.py

This is the JSON support component of Alvaro's changes, I had to edit a couple of commits to try and keep the branch on topic so sorry about my name appearing in the commits.
Relates to #8

Json support

---

pydiscourse/client.py

Assuming #9 is OK, this is the second set of changes related to #8. I've tried to pick non breaking changes for this batch and when they are merged I will create a branch for the last few.

New api methods

---

pydiscourse/client.py

Use put() while trying to activate or deactivate user account.
Signed-off-by: Lakshmipathi.G <Lakshmipathi.G@giis.co.in>

Fix activate and deactivate call

---

.github/workflows/test.yml
README.rst
setup.py
tests/test_client.py

Add GitHub Actions testing workflow

---

pydiscourse/client.py

Added a couple of methods for invites and invite links, that I needed.

Added invite() and invite_link() methods

---

.github/workflows/test.yml

Run test workflow on pull request

---

pydiscourse/client.py

Due to some changes in the Discourse API, certain methods now work better if redirects are allowed.
Get `/c/{id}.json` will redirect to `/c/{category_slug}.json` which will cause the client.category_topics(id) method to fail as the redirect is not followed by default.
Now the keyword arguments to requests.request can be overridden by individual methods.
This is [implemented for `.category_topics`](https://github.com/bennylope/pydiscourse/pull/34/files#diff-0b54ff8984472a0c8d41e7d4e8ec5695L491-R497) to override `allow_redirects=False`.
For any method to override (or set) a specific request.request keyword argument, `request_kwargs` can now be passed to the HTTP verb method and it will be passed through to `client._request`.
```python
def category_topics(self, category_id, **kwargs):
return …
```

Allow client methods to override requests kwargs

---

pydiscourse/client.py

Fixes 404 caused by new endpoint, see https://review.discourse.org/t/fix-move-hp-request-from-users-to-token-10795/15871

Fix endpoint used for user creation (closes #46)

---

pydiscourse/client.py

This PR implements new routes : 
- user_by_id (admin)
- user_by_email (admin)
- top_topics
- post_by_id
- reset_bump_date
- category_latest_topics
- get_site_settings
- data_explorer_query (plugin)
- notifications
This is a merge from our team fork from tindie/pydiscourse.
We want to merge back now that the PyPi version seems maintained.
Thanks !

Implement new routes

---

src/pydiscourse/client.py

Added option to fetch all categories including subcategories. https://docs.discourse.org/#operation/getSite

Add option to fetch all categories including subcategories

---

src/pydiscourse/client.py

Closes #60
This handles the case where we get an early HTTP 429 error, without a JSON body telling us how long to wait.

Handle HTTP 429 errors that are not JSON-encoded

---

.github/workflows/test.yml

Add Python 3.11 to test matrix

---

src/pydiscourse/client.py

The Discourse API will paginate group members (see [here](https://docs.discourse.org/#tag/Groups/operation/listGroupMembers)), in my experience returning at most 50 at a time. Since the docstring for `group_members` says to return them all, a loop over the pagination is needed. This PR adds that loop.

Respect pagination when returning all group members

---

CONTRIBUTING.rst
requirements.txt
setup.cfg
src/pydiscourse/__init__.py
src/pydiscourse/client.py
src/pydiscourse/sso.py
tests/conftest.py
tests/test_client.py
tests/test_sso.py
tox.ini

Clean up tests, Python support

---

tests/test_client.py
tox.ini

Replace mocks and increase coverage requirement

---

HISTORY.rst
src/pydiscourse/__init__.py

Update version for release

---

src/pydiscourse/client.py
tests/test_client.py

add anonymize user enpoint
EDIT: sorry I messed a bit with git... The first commit is already in master.

add anonymize user enpoint

---

README.rst

Add some python highlighted section

Readme codehighligth
